# Generated by Django 4.0 on 2021-12-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_purchase',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
