# Generated by Django 4.0 on 2021-12-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_registry', '0002_purchase_price_alter_purchase_date_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_trip', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'dates',
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_registry.date'),
        ),
    ]
